### ISSUE TITLE
android version 7でのエラー表示を戻すときのエラー

### ISSUE THREAD

**Issue by SnowDango** [YukiTeito/NumAc#4]

**Comment by SnowDango** [comment]
```
2020-12-03 15:18:50.157 30236-30236/com.snowdango.numac I/HwPointEventFilter: do not support AFT because of no config
2020-12-03 15:18:50.242 30236-30275/com.snowdango.numac E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.snowdango.numac, PID: 30236
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7377)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1197)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5261)
        at android.view.View.invalidateInternal(View.java:13721)
        at android.view.View.invalidate(View.java:13656)
        at android.view.View.invalidate(View.java:13640)
        at android.widget.TextView.checkForRelayout(TextView.java:7668)
        at android.widget.TextView.setText(TextView.java:4586)
        at android.widget.TextView.setText(TextView.java:4443)
        at android.widget.TextView.setText(TextView.java:4418)
        at com.snowdango.numac.activity.main.MainActivity$commandExec$1.invokeSuspend(MainActivity.kt:147)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-12-03 15:18:50.246 30236-30236/com.snowdango.numac I/HwResourcesImpl: load icon id : 7f0e0004, pkgName : com.skype.raider
2020-12-03 15:18:50.246 30236-30236/com.snowdango.numac W/CfgFilePolicy: No config file found for:xml/hw_launcher_load_icon.xml
2020-12-03 15:18:50.247 30236-30236/com.snowdango.numac W/CfgFilePolicy: CFG_DIRS length : 10
2020-12-03 15:18:50.247 30236-30236/com.snowdango.numac E/HwResourcesImpl: readDefaultConfig : FileNotFoundException
2020-12-03 15:18:50.247 30236-30236/com.snowdango.numac W/CfgFilePolicy: No config file found for:/themes/diff/icons
2020-12-03 15:18:50.247 30236-30236/com.snowdango.numac W/CfgFilePolicy: CFG_DIRS length : 10
2020-12-03 15:18:50.249 30236-30236/com.snowdango.numac I/HwResourcesImpl: icon : com.skype.raider found in app
2020-12-03 15:18:50.264 30236-30275/com.snowdango.numac I/Process: Sending signal. PID: 30236 SIG: 9
```

**Comment by SnowDango** [comment]
該当部分

```
// error::after
    private fun errorViewAfter(){
        coroutineScope.launch(Dispatchers.Default){
            delay(500)
            textView.text = getString(R.string.please_push_number)
            textView.setTextColor(getColor(R.color.fullactivityText))
        }
    }
```
